# Generated by Django 4.1.4 on 2022-12-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_expired", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=25)),
                ("temperature", models.CharField(default="", max_length=25)),
                ("min_temp", models.CharField(default="", max_length=25)),
                ("max_temp", models.CharField(default="", max_length=25)),
                ("wind_speed", models.CharField(default="", max_length=25)),
                ("humidity", models.CharField(default="", max_length=25)),
                ("next_min_temp", models.CharField(default="", max_length=25)),
                ("next_max_temp", models.CharField(default="", max_length=25)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
